### PR TITLE
Simplify CLI option handling

### PR DESCRIPTION
**Pull request by matthiasschaub**
### Description
Simplify CLI option handling by only allowing one option at a time to be added.
Also rename variable names to be more concise.

### Checklist
- [x] I have updated my branch to `main` (e.g. through `git rebase main`)
- [x] My code follows the [style guide](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#pre-commit) before committing
- ~[ ] I have commented my code~
- ~[ ] I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-analyst/blob/main/docs/development_setup.md#tests)~
- [x] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CHANGELOG.md)

### CODE REVIEW

**Comment by Hagellach37** [comment]
Hey looks also good to me. But I didn't check locally.

As a general question: How much of this is tested in the CI in Jenkins?

**Comment by matthiasschaub** [comment]
> Hey looks also good to me. But I didn't check locally.
> 
> As a general question: How much of this is tested in the CI in Jenkins?

There are a couple of tests for the CLI:
- Unittests of all the list-... commands: https://github.com/GIScience/ohsome-quality-analyst/blob/main/workers/tests/unittests/test_cli.py
- Unittest of cli_opt int_or_str_param_type class: https://github.com/GIScience/ohsome-quality-analyst/blob/main/workers/tests/unittests/test_cli_opts.py
- integration tests of create indicator/report: https://github.com/GIScience/ohsome-quality-analyst/blob/main/workers/tests/integrationtests/test_cli.py

All tests are run by the CI.
@Hagellach37 does this answer your question?

**Comment by Hagellach37** [comment]
Hey @matthiasschaub ,
yep I think that this answers my question. I also checked locally now.

Could you also take a look at this issue #58 

It is also related to the CLI parameters and thus it would fit good to address it here as well. It seems to be that there is a bug  when the feature_id parameter is not set.

**Comment by Hagellach37** [comment]
Hey @matthiasschaub ,
in general the changes look good to me. Could you please check why the `test_cli.py` test fails. Does it also fail for you?

**Comment by matthiasschaub** [comment]
> Hey @matthiasschaub ,
> in general the changes look good to me. Could you please check why the `test_cli.py` test fails. Does it also fail for you?
> 
> ```
> FAILED tests/integrationtests/test_cli.py::TestCliIntegration::test_create_indicator - AssertionError: 1 != 0
> FAILED tests/integrationtests/test_cli.py::TestCliIntegration::test_create_indicator_custom_fid_field_int - AssertionError: 1 != 0
> FAILED tests/integrationtests/test_cli.py::TestCliIntegration::test_create_indicator_custom_fid_field_str - AssertionError: 1 != 0
> FAILED tests/integrationtests/test_cli.py::TestCliIntegration::test_create_report - AssertionError: 1 != 0
> FAILED tests/integrationtests/test_cli.py::TestCliIntegration::test_create_report_custom_fid_field_int - AssertionError: 1 != 0
> FAILED tests/integrationtests/test_cli.py::TestCliIntegration::test_create_report_custom_fid_field_str - AssertionError: 1 != 0
> FAILED tests/integrationtests/test_cli.py::TestCliIntegration::test_get_available_regions - AssertionError: 1 != 0
> ```

@Hagellach37 
I can not reproduce this issues (Also the CI runs successful). Is this the only test file which produces failing tests? What happens if you execute `oqt list-regions`?

**Review by Hagellach37 — APPROVED** [review]

**Review by Hagellach37 — APPROVED** [review]

**Pull request merged**
